### ISSUE TITLE
Minecraft 1.20.2 "Discord Integration failed to connect"

### ISSUE THREAD

**Issue by iggyvilla** [dominik-korsa/discord-integration#74]
Using Minecraft version 1.20.2 and Discord Integration version 3.5.0. Messages in Minecraft get sent via webhook, but Discord messages don't get sent into Minecraft reliably (some restarts it works, sometimes it doesn't).

```
[22:39:13] [Server thread/INFO]: Discord Integration failed to connect
[22:39:13] [Server thread/WARN]: reactor.core.publisher.Sinks$EmissionException: Spec. Rule 1.3 - onSubscribe, onNext, onError and onComplete signaled to a Subscriber MUST be signaled serially.
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:56)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//discord4j.gateway.GatewayClient.lambda$send$0(GatewayClient.java:115)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:196)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onSubscribe(MonoIgnoreElements.java:72)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.Mono.subscribe(Mono.java:4490)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.Mono.subscribe(Mono.java:4475)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:85)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:182)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
[22:39:13] [Server thread/WARN]:        at DiscordIntegration-3.5.0.jar//reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
[22:39:13] [Server thread/WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[22:39:13] [Server thread/WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[22:39:13] [Server thread/WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:39:13] [Server thread/WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:39:13] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by AqueleHaru** [comment]
same here.

```
[21:16:49] [Server thread/WARN] [/]: reactor.core.publisher.Sinks$EmissionException: Spec. Rule 1.3 - onSubscribe, onNext, onError and onComplete signaled to a Subscriber MUST be signaled serially.
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:56)
[21:16:49] [Server thread/WARN] [/]:    at discord4j.gateway.GatewayClient.lambda$send$0(GatewayClient.java:115)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:196)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onSubscribe(MonoIgnoreElements.java:72)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.Mono.subscribe(Mono.java:4490)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.Mono.subscribe(Mono.java:4475)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:85)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:182)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
[21:16:49] [Server thread/WARN] [/]:    at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
[21:16:49] [Server thread/WARN] [/]:    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:16:49] [Server thread/WARN] [/]:    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[21:16:49] [Server thread/WARN] [/]:    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:16:49] [Server thread/WARN] [/]:    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:16:49] [Server thread/WARN] [/]:    at java.base/java.lang.Thread.run(Thread.java:1583)
```
